title: Oracle Cloud Migrations Onboarding
description: Deploy the resources required for the Oracle Cloud Migration service to function properly.
schemaVersion: 1.1.0
version: "20190304"
variableGroups:
  - title: "Migration Root Location"
    variables:
      - ${compartment_ocid}
  - title: "Global Resources"
    variables:
      - ${primary_prerequisite_stack}
  - title: "Enabled Migrations"
    visible: primary_prerequisite_stack
    variables:
      - ${enabled_migration_scenario}
      - ${add_vmware_to_oci}
      - ${add_vmware_to_olvm}
      - ${add_aws_to_oci}
  - title: "Replication Location"
    variables:
      - ${replication_bucket}
      - ${create_replication_bucket}
  - title: "Optional Resources"
    visible: primary_prerequisite_stack
    variables: 
      - ${migration_groups}
      - ${remote_agent_logging}
      - ${hydration_agent_logging}
  - title: "Remote Agent Appliance Logging"
    visible: 
      and: 
        - remote_agent_logging
        - primary_prerequisite_stack
    variables:
      - ${ocb-service-tenancy-ocid}
  - title: "Hydration Agent Logging"
    visible: 
      and:
        - hydration_agent_logging
        - primary_prerequisite_stack
    variables:
      - ${ocm-service-tenancy-ocid}
  - title: "Hidden"
    visible: false
    variables: 
      - ${tenancy_ocid}
      - ${create_cloud_migrations_tag_namespace_and_tag_definitions}
variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    description: "The parent compartment where the working compartments (Migration and MigrationSecrets) will be created."
    title: "Migration Root Compartment"
    required: true
  create_replication_bucket:
    type: boolean
    description: "Create a new Object Storage bucket used for data replication."
    title: "Create a new replication bucket?"
    required: true
    default: true
  replication_bucket:
    type: string
    description: "Name of an existing bucket or name of the replication bucket to be created."
    title: "Replication Bucket Name"
    required: false
  primary_prerequisite_stack:
    type: boolean
    description: "Uncheck if working compartments, tag namespace, and service policies have already been deployed."
    title: "Primary Prerequisite Stack"
    required: true
    default: true
  enabled_migration_scenario:
    type: enum
    description: "Select the enabled migration scenario. Note: \"VMware to OLVM\" (Limited Availability) migration is available for selected customers only during the LA phase."
    title: "Enabled Migration Scenario"
    required: true
    visible: primary_prerequisite_stack
    enum:
      - "VMware to OCI"
      - "VMWare to OLVM (Limited Availability)"
      - "AWS to OCI"
  add_vmware_to_oci:
    type: boolean
    description: "Optionally enable VMware to OCI migrations in addition to the primary scenario."
    title: "VMware to OCI"
    required: false
    default: false
    visible:
      and:
        - primary_prerequisite_stack
        - not:
          - eq:
            - enabled_migration_scenario
            - "VMware to OCI"
        - not:
          - eq:
            - enabled_migration_scenario
            - ""
  add_vmware_to_olvm:
    type: boolean
    description: "Optionally enable VMware to OLVM migrations in addition to the primary scenario. Note: \"VMware to OLVM\" (Limited Availability) migration is available for selected customers only during the LA phase."
    title: "VMware to OLVM (Limited Availability)"
    required: false
    default: false
    visible:
      and:
        - primary_prerequisite_stack
        - not:
          - eq:
            - enabled_migration_scenario
            - "VMware to OLVM"
        - not:
          - eq:
            - enabled_migration_scenario
            - ""
  add_aws_to_oci:
    type: boolean
    description: "Optionally enable AWS to OCI migrations in addition to the primary scenario."
    title: "AWS to OCI"
    required: false
    default: false
    visible:
      and:
        - primary_prerequisite_stack
        - not:
          - eq:
            - enabled_migration_scenario
            - "AWS to OCI"
        - not:
          - eq:
            - enabled_migration_scenario
            - ""
  migration_groups:
    type: boolean
    description: "Create base policies for migration administrators and migration operators."
    title: "Migration Service User Groups"
    required: false
    default: false
  remote_agent_logging:
    type: boolean
    description: "Create service policies allowing Remote Agent Appliances upload logs."
    title: "Enable Remote Agent Appliance logging"
    required: false
    default: false
    visible:
      or:
        - eq:
            - enabled_migration_scenario
            - "VMware to OCI"
        - eq:
            - enabled_migration_scenario
            - "VMware to OLVM"
        - add_vmware_to_oci
        - add_vmware_to_olvm
  hydration_agent_logging:
    type: boolean
    description: "Create service policies allowing Hydration Agents to upload logs."
    title: "Enable Hydration Agent logging"
    required: false
    default: false
    visible:
      or:
        - eq:
            - enabled_migration_scenario
            - "VMware to OCI"
        - eq:
            - enabled_migration_scenario
            - "AWS to OCI"
        - add_vmware_to_oci
        - add_aws_to_oci
  ocb-service-tenancy-ocid:
    type: string
    description: "Realm OCID of the Oracle Cloud Bridge service tenancy."
    title: "Oracle Cloud Bridge service tenancy"
    required: true
    default: "ocid1.tenancy.oc1..aaaaaaaahr2xcduf4knzkzhkzt442t66bpqt3aazss6cy2ll6x4xj3ci7tiq"
  ocm-service-tenancy-ocid:
    type: string
    description: "Realm OCID of the Oracle Cloud Migrations service tenancy."
    title: "Oracle Cloud Migrations service tenancy"
    required: true
    default: "ocid1.tenancy.oc1..aaaaaaaartv6j5muce2s4djz7rvfn2vwceq3cnue33d72isntnlfmi7huv7q"
